services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1 # 소프트 리미트: 무제한
        hard: -1 # 하드 리미트: 무제한
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  fluent-bit:
    image: fluent/fluent-bit:4.0
    container_name: fluent-bit
    ports:
      # 모니터링 포트
      - "2020:2020"
      # TCP 로그 수신 포트 (HTTP 로그)
      - "24224:24224"
    volumes:
      # Fluent Bit 핵심 설정 파일들
      - ./fluent-bit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    environment:
      # TCP 기반 로그 수집에 최적화된 환경변수들
      - FLB_LOG_LEVEL=info
      # Elasticsearch 연결 정보
      - FLB_ES_HOST=elasticsearch
      - FLB_ES_PORT=9200
      # 호스트네임 정보
      - HOSTNAME=fluent-bit
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: /fluent-bit/bin/fluent-bit --config=/fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:2020/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  elasticsearch_data:
    driver: local
  # Fluent Bit 파일 위치 추적용 볼륨
  fluent_bit_storage:
    driver: local

networks:
  elastic:
    driver: bridge