server:
  port: 8080
  shutdown: graceful

logging:
  config: classpath:log4j2-spring-local.xml

spring:

  application:
    name: todo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

